# This workflow will build a Java project with Maven

# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI build and save docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-save-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Maven build
        run: mvn -B clean install

      - name: build docker image
        run: docker build -t keycloak:latest .

      - name: Save Docker Image as Tarball
        run: |
          docker save -o keyclockcustom-image.tar keycloak:latest
